import {
  PageIcon,
  DashboardIcon,
  PersonIcon,
  PresIcon,
  PersonRoundedIcon,
  HeadsetIcon,
  DocFlowIcon,
  SupportIcon,
  PersonalManagerIcon,
  LoyalityIcon,
  CargoIcon,
  ShieldIcon,
  InfoIcon,
  LogoIcon,
  MouseIcon,
  ChevronIcon,
  ClockIcon,
  AwardsIcon,
  WarrantyIcon,
  MapIcon,
  BoxIcon,
  NotificationsIcon,
  PersonalSupportIcon,
  FlagIcon,
  DefenseIcon,
  LorryIcon,
} from "@/ui-kit/icons";

export const iconOptions = {
  LogoIcon: <LogoIcon />,
  InfoIcon: <InfoIcon />,
  MouseIcon: <MouseIcon />,
  ChevronIcon: <ChevronIcon />,
  PageIcon: <PageIcon />,
  DashboardIcon: <DashboardIcon />,
  PresIcon: <PresIcon />,
  PersonIcon: <PersonIcon />,
  PersonRoundedIcon: <PersonRoundedIcon />,
  HeadsetIcon: <HeadsetIcon />,
  DocFlowIcon: <DocFlowIcon />,
  SupportIcon: <SupportIcon />,
  PersonalManagerIcon: <PersonalManagerIcon />,
  LoyalityIcon: <LoyalityIcon />,
  CargoIcon: <CargoIcon />,
  ShieldIcon: <ShieldIcon />,
  ClockIcon: <ClockIcon />,
  AwardsIcon: <AwardsIcon />,
  WarrantyIcon: <WarrantyIcon />,
  MapIcon: <MapIcon />,
  BoxIcon: <BoxIcon />,
  NotificationsIcon: <NotificationsIcon />,
  FlagIcon: <FlagIcon />,
  PersonalSupportIcon: <PersonalSupportIcon />,
  DefenseIcon: <DefenseIcon />,
  LorryIcon: <LorryIcon />,
};
