version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "pgdbuser"
      POSTGRES_PASSWORD: "pass4pgdbuser"
    ports:
      - "5432:5432"