import {
  PageIcon,
  DashboardIcon,
  PersonIcon,
  PresIcon,
  PersonRoundedIcon,
  HeadsetIcon,
  DocFlowIcon,
  SupportIcon,
  PersonalManagerIcon,
  LoyalityIcon,
  CargoIcon,
  ShieldIcon,
  InfoIcon,
  LogoIcon,
  MouseIcon,
  ChevronIcon,
  ClockIcon,
  AwardsIcon,
  WarrantyIcon,
  MapIcon,
  BoxIcon,
  NotificationsIcon,
  PersonalSupportIcon,
  FlagIcon,
  DefenseIcon,
  LorryIcon,
  Box2Icon,
  Lorry2Icon,
  HexIcon,
  CheckIcon,
  ControlsIcon,
  Controls2Icon,
  BagIcon,
  PocketIcon,
  CheckRoundedIcon,
  DownloadIcon,
  Lorry3Icon,
  Lorry4Icon,
} from "@/ui-kit/icons";

export const iconOptions = {
  LogoIcon: <LogoIcon />,
  InfoIcon: <InfoIcon />,
  MouseIcon: <MouseIcon />,
  ChevronIcon: <ChevronIcon />,
  PageIcon: <PageIcon />,
  DownloadIcon: <DownloadIcon />,
  DashboardIcon: <DashboardIcon />,
  PresIcon: <PresIcon />,
  PersonIcon: <PersonIcon />,
  PersonRoundedIcon: <PersonRoundedIcon />,
  HeadsetIcon: <HeadsetIcon />,
  DocFlowIcon: <DocFlowIcon />,
  SupportIcon: <SupportIcon />,
  ControlsIcon: <ControlsIcon />,
  PersonalManagerIcon: <PersonalManagerIcon />,
  LoyalityIcon: <LoyalityIcon />,
  CargoIcon: <CargoIcon />,
  BagIcon: <BagIcon />,
  PocketIcon: <PocketIcon />,
  ShieldIcon: <ShieldIcon />,
  ClockIcon: <ClockIcon />,
  AwardsIcon: <AwardsIcon />,
  WarrantyIcon: <WarrantyIcon />,
  MapIcon: <MapIcon />,
  BoxIcon: <BoxIcon />,
  Controls2Icon: <Controls2Icon />,
  NotificationsIcon: <NotificationsIcon />,
  FlagIcon: <FlagIcon />,
  PersonalSupportIcon: <PersonalSupportIcon />,
  DefenseIcon: <DefenseIcon />,
  LorryIcon: <LorryIcon />,
  Box2Icon: <Box2Icon />,
  Lorry2Icon: <Lorry2Icon />,
  Lorry3Icon: <Lorry3Icon />,
  Lorry4Icon: <Lorry4Icon />,
  HexIcon: <HexIcon />,
  CheckIcon: <CheckIcon />,
  CheckRoundedIcon: <CheckRoundedIcon />,
};
